apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-green
  labels:
    app: chat-green
spec:
  selector:
    matchLabels:
      app: chat-green
  template:
    metadata:
      labels:
        app: chat-green
    spec:
      containers:
      - name: chat-green
        image: diegotc/chat-channel
        ports:
        - containerPort: 5000

